# Generated by Django 3.1 on 2020-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directions',
            new_name='Direction',
        ),
    ]
