# Generated by Django 3.1 on 2020-09-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_auto_20200909_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='specialname',
        ),
    ]
